import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
 

// Definição da fonte Saira para o texto principal
const sairaSans = Saira({
  variable: "--font-saira-sans",
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700']
});

// Definição da fonte Saira para estilo mono
const sairaMono = Saira({
  variable: "--font-saira-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sairaSans.variable} ${sairaMono.variable}`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}